receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    send_batch_size: 8192
    send_batch_max_size: 0
    timeout: 200

exporters:
  logging:
  otlp/data-prepper:
    endpoint: "data-prepper.dev-testnet-infra.local:21890"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/data-prepper, logging]
    logs:
      receivers: [otlp]
      exporters: [otlp/data-prepper]
